gradle.root=android_tv_frontend
settings=android_tv_frontend/settings.gradle
wrapper=android_tv_frontend/gradlew
modules=:app,:list,:utilities
apk.debug.path=android_tv_frontend/app/build/outputs/apk/debug/app-debug.apk
