.PHONY: build assemble assembleDebug clean

build:
	./android_tv_frontend/gradlew :app:assembleDebug

assemble:
	./android_tv_frontend/gradlew :app:assemble

assembleDebug:
	./android_tv_frontend/gradlew :app:assembleDebug

clean:
	./android_tv_frontend/gradlew clean
