pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "android-tv-hello-world-delegated-root-kts"

include(":app")
include(":list")
include(":utilities")
project(":app").projectDir = file("android_tv_frontend/app")
project(":list").projectDir = file("android_tv_frontend/list")
project(":utilities").projectDir = file("android_tv_frontend/utilities")
