android.gradle.root=android_tv_frontend
android.gradle.wrapper=android_tv_frontend/gradlew
android.settings.files=android_tv_frontend/settings.gradle,android_tv_frontend/settings.gradle.kts
android.modules=:app,:list,:utilities
android.apk.debug.path=android_tv_frontend/app/build/outputs/apk/debug/app-debug.apk
